### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by Khanabied** [Simatwa/smartbetsAPI#1]
I have installed the requirements but on running smartbetAPi i end up with this error:

This site can’t be reachedThe webpage at http://127.0.0.1:8000/ might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

All requirements are all installed. Please help on what might be the error, or I may be doing wrong or overlooked.

Thanks.

**Comment by Simatwa** [comment]
There was a bug in the _error response's content-type_. Currently [fixed](https://github.com/Simatwa/smartbetsAPI/commit/848827a1aac1de3656262ab1d9191ea729660dd9). 
Thanks for the concern.

**Comment by Khanabied** [comment]
hello 
ran smartbetsAPI <mypassword from smartbets>

but on browser it says {"comment":null,"message":"Kindly login!"}

is there a place in code am supposed to input credentials? coz instructions say dun smartbetsAPI password.
thanks

**Comment by Simatwa** [comment]
Be informed that as from version 1.0.5 all responses are now fully jsonified thus works best at programming level as shown in [this script](https://github.com/Simatwa/smartbetsAPI/blob/main/examples/bet_at_api_level.py),  and less effective at *browsers*.

All said, this tweak can help at the browser level.
```
#Login 
http://localhost:8000/login?user={username}&paswd={password} 
#Make requests
http://localhost:8000/predict?home=Arsenal&away=Liverpool&net=True
```
