### ISSUE TITLE
WARNING  REQUESTS

### ISSUE THREAD

**Issue by fera765** [Simatwa/smartbetsAPI#2]
Apparently when there is a lot of request it starts with an error when making a new request 

INFO : Retrying - https://www.google.com/search?q=Aucas+fc+in+soccerway.com
01:55:48 - WARNING : 429 - Too Many Requests

**Comment by Simatwa** [comment]
It is a common thing with Google though can be minimized by proxies. Append `--enable-proxy` while starting the REST API. Hope that helps at the moment.
